swagger: "2.0"
info:
  version: "1.0.0"
  title: "Messenger"
tags:
- name: "Messages"
  description: "Everything about Messages"
  externalDocs:
    description: "Find out more about this messenger"
    url: "https://cc-messenger-app.herokuapp.com/"
schemes:
- "https"
- "http"
securityDefinitions:
  BasicAuth:
    type: basic
paths:
  /messages:
    post:
      tags:
      - "Messages"
      summary: "Send a new message"
      description: ""
      operationId: "sendMessage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Message object that needs to be sent"
        required: true
        schema:
          $ref: "#/definitions/CreateMessage"
      responses:
        422:
          description: "Invalid input"
      security:
      - BasicAuth: []
    put:
      tags:
      - "Messages"
      summary: "Update Message"
      description: ""
      operationId: "updateMessage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Message object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/PutMessage"
      responses:
        404:
          description: "Message not found"
        422:
          description: "Validation exception"
      security:
      - BasicAuth: []
  /messages/{userId}:
    get:
      tags:
      - "Messages"
      summary: "Get unread messages"
      description: ""
      operationId: "readMessages"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "userId of user which messages to get"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "List of unread messages of user with userId"
        405:
          description: "Invalid input"
      security:
      - BasicAuth: []
  /messages/{userId}/all:
    get:
      tags:
      - "Messages"
      summary: "Get all messages for userId"
      description: ""
      operationId: "readAllMessages"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "userId of user which messages to get"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "List of unread messages of user with userId"
        405:
          description: "Invalid input"
      security:
      - BasicAuth: []
  /messages/{messageId}/delete:
    delete:
      tags:
      - "Messages"
      summary: "Delete Message"
      description: ""
      operationId: "deleteMessage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "messageId"
        in: "path"
        description: "Message id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Message not found"
      security:
      - BasicAuth: []
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      password:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
    xml:
      name: "User"
  CreateMessage:
    type: "object"
    required:
    - "senderId"
    - "text"
    - "receivers"
    properties:
      senderId:
        type: "integer"
        format: "int64"
      text:
        type: "string"
        example: "Hello, how are you?"
      receivers:
        type: "array"
        items:
          type: "integer"
    xml:
      name: "CreateMessage"
  PutMessage:
    type: "object"
    required:
    - "id"
    - "senderId"
    - "text"
    properties:
      id:
        type: "integer"
        format: "int64"
      senderId:
        type: "integer"
        format: "int64"
      text:
        type: "string"
        example: "Hello, how are you?"
    xml:
      name: "PutMessage"
  Message:
    type: "object"
    required:
    - "id"
    - "text"
    - "read"
    properties:
      id:
        type: "integer"
        format: "int64"
      senderId:
        type: "integer"
        format: "int64"
      text:
        type: "string"
        example: "Hello, how are you?"
      read:
        type: "array"
        items:
          $ref: "#/definitions/ReadConfirmation"
    xml:
      name: "Message"
  ReadConfirmation:
    type: "object"
    properties:
      message_read:
        type: "boolean"
      receiver_id:
        type: "integer"
    xml:
      name: "ReadConfirmation"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
